---
dependency:
  name: galaxy
  options:
    role-file: .molecule-requirements.yml
driver:
  name: podman
platforms:
  - name: instance
    image: "${IMAGE}"
    command: ""
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    converge: ../../.molecule-converge.yml
verifier:
  name: ansible
